export const NAMIBIA_REGIONS = [
  "Zambezi",
  "Kavango East",
  "Kavango West",
  "Kunene",
  "Ohangwena",
  "Omaheke",
  "Omusati",
  "Oshana",
  "Oshikoto",
  "Otjozondjupa",
  "Erongo",
  "Hardap",
  "Karas",
  "Khomas",
] as const;

export const NAMIBIA_TOWNS_CITIES = [
  "Windhoek",
  "Walvis Bay",
  "Swakopmund",
  "Okahandja",
  "Rehoboth",
  "Otjiwarongo",
  "Okakarara",
  "Karibib",
  "Omaruru",
  "Usakos",
  "Henties Bay",
  "Arandis",
  "Gobabis",
  "Otavi",
  "Tsumeb",
  "Grootfontein",
  "Okongo",
  "Eenhana",
  "Ongwediva",
  "Oshakati",
  "Ondangwa",
  "Outapi",
  "Opuwo",
  "Khorixas",
  "Rundu",
  "Nkurenkuru",
  "Katima Mulilo",
  "Keetmanshoop",
  "Lüderitz",
  "Mariental",
  "Maltahöhe",
  "Karasburg",
  "Ariamsvlei",
  "Oranjemund",
  "Aranos",
  "Bethanie",
  "Karasburg",
] as const;
