// Nationalities (demonyms) keyed by the country names in countries.ts.
// Keep in sync with src/ui/utils/nationalities.ts (frontend).
export const COUNTRY_NATIONALITIES: [country: string, nationality: string][] = [
  ["Afghanistan", "Afghan"],
  ["Albania", "Albanian"],
  ["Algeria", "Algerian"],
  ["Andorra", "Andorran"],
  ["Angola", "Angolan"],
  ["Antigua and Barbuda", "Antiguan and Barbudan"],
  ["Argentina", "Argentine"],
  ["Armenia", "Armenian"],
  ["Australia", "Australian"],
  ["Austria", "Austrian"],
  ["Azerbaijan", "Azerbaijani"],
  ["Bahamas", "Bahamian"],
  ["Bahrain", "Bahraini"],
  ["Bangladesh", "Bangladeshi"],
  ["Barbados", "Barbadian"],
  ["Belarus", "Belarusian"],
  ["Belgium", "Belgian"],
  ["Belize", "Belizean"],
  ["Benin", "Beninese"],
  ["Bhutan", "Bhutanese"],
  ["Bolivia", "Bolivian"],
  ["Bosnia and Herzegovina", "Bosnian and Herzegovinian"],
  ["Botswana", "Motswana"],
  ["Brazil", "Brazilian"],
  ["Brunei", "Bruneian"],
  ["Bulgaria", "Bulgarian"],
  ["Burkina Faso", "Burkinabe"],
  ["Burundi", "Burundian"],
  ["Cabo Verde", "Cabo Verdean"],
  ["Cambodia", "Cambodian"],
  ["Cameroon", "Cameroonian"],
  ["Canada", "Canadian"],
  ["Central African Republic", "Central African"],
  ["Chad", "Chadian"],
  ["Chile", "Chilean"],
  ["China", "Chinese"],
  ["Colombia", "Colombian"],
  ["Comoros", "Comorian"],
  ["Congo (Congo-Brazzaville)", "Congolese (Republic of the Congo)"],
  ["Costa Rica", "Costa Rican"],
  ["Côte d’Ivoire", "Ivorian"],
  ["Croatia", "Croatian"],
  ["Cuba", "Cuban"],
  ["Cyprus", "Cypriot"],
  ["Czechia", "Czech"],
  ["Democratic Republic of the Congo", "Congolese (DRC)"],
  ["Denmark", "Danish"],
  ["Djibouti", "Djiboutian"],
  ["Dominica", "Dominican (Dominica)"],
  ["Dominican Republic", "Dominican (Dominican Republic)"],
  ["Ecuador", "Ecuadorian"],
  ["Egypt", "Egyptian"],
  ["El Salvador", "Salvadoran"],
  ["Equatorial Guinea", "Equatorial Guinean"],
  ["Eritrea", "Eritrean"],
  ["Estonia", "Estonian"],
  ["Eswatini", "Swazi"],
  ["Ethiopia", "Ethiopian"],
  ["Fiji", "Fijian"],
  ["Finland", "Finnish"],
  ["France", "French"],
  ["Gabon", "Gabonese"],
  ["Gambia", "Gambian"],
  ["Georgia", "Georgian"],
  ["Germany", "German"],
  ["Ghana", "Ghanaian"],
  ["Greece", "Greek"],
  ["Grenada", "Grenadian"],
  ["Guatemala", "Guatemalan"],
  ["Guinea", "Guinean"],
  ["Guinea-Bissau", "Bissau-Guinean"],
  ["Guyana", "Guyanese"],
  ["Haiti", "Haitian"],
  ["Honduras", "Honduran"],
  ["Hungary", "Hungarian"],
  ["Iceland", "Icelandic"],
  ["India", "Indian"],
  ["Indonesia", "Indonesian"],
  ["Iran", "Iranian"],
  ["Iraq", "Iraqi"],
  ["Ireland", "Irish"],
  ["Israel", "Israeli"],
  ["Italy", "Italian"],
  ["Jamaica", "Jamaican"],
  ["Japan", "Japanese"],
  ["Jordan", "Jordanian"],
  ["Kazakhstan", "Kazakh"],
  ["Kenya", "Kenyan"],
  ["Kiribati", "I-Kiribati"],
  ["Kuwait", "Kuwaiti"],
  ["Kyrgyzstan", "Kyrgyz"],
  ["Laos", "Lao"],
  ["Latvia", "Latvian"],
  ["Lebanon", "Lebanese"],
  ["Lesotho", "Mosotho"],
  ["Liberia", "Liberian"],
  ["Libya", "Libyan"],
  ["Liechtenstein", "Liechtensteiner"],
  ["Lithuania", "Lithuanian"],
  ["Luxembourg", "Luxembourgish"],
  ["Madagascar", "Malagasy"],
  ["Malawi", "Malawian"],
  ["Malaysia", "Malaysian"],
  ["Maldives", "Maldivian"],
  ["Mali", "Malian"],
  ["Malta", "Maltese"],
  ["Marshall Islands", "Marshallese"],
  ["Mauritania", "Mauritanian"],
  ["Mauritius", "Mauritian"],
  ["Mexico", "Mexican"],
  ["Micronesia", "Micronesian"],
  ["Moldova", "Moldovan"],
  ["Monaco", "Monégasque"],
  ["Mongolia", "Mongolian"],
  ["Montenegro", "Montenegrin"],
  ["Morocco", "Moroccan"],
  ["Mozambique", "Mozambican"],
  ["Myanmar (Burma)", "Burmese"],
  ["Namibia", "Namibian"],
  ["Nauru", "Nauruan"],
  ["Nepal", "Nepali"],
  ["Netherlands", "Dutch"],
  ["New Zealand", "New Zealander"],
  ["Nicaragua", "Nicaraguan"],
  ["Niger", "Nigerien"],
  ["Nigeria", "Nigerian"],
  ["North Korea", "North Korean"],
  ["North Macedonia", "Macedonian"],
  ["Norway", "Norwegian"],
  ["Oman", "Omani"],
  ["Pakistan", "Pakistani"],
  ["Palau", "Palauan"],
  ["Palestine", "Palestinian"],
  ["Panama", "Panamanian"],
  ["Papua New Guinea", "Papua New Guinean"],
  ["Paraguay", "Paraguayan"],
  ["Peru", "Peruvian"],
  ["Philippines", "Filipino"],
  ["Poland", "Polish"],
  ["Portugal", "Portuguese"],
  ["Qatar", "Qatari"],
  ["Romania", "Romanian"],
  ["Russia", "Russian"],
  ["Rwanda", "Rwandan"],
  ["Saint Kitts and Nevis", "Kittitian and Nevisian"],
  ["Saint Lucia", "Saint Lucian"],
  ["Saint Vincent and the Grenadines", "Vincentian"],
  ["Samoa", "Samoan"],
  ["San Marino", "Sammarinese"],
  ["Sao Tome and Principe", "São Toméan"],
  ["Saudi Arabia", "Saudi Arabian"],
  ["Senegal", "Senegalese"],
  ["Serbia", "Serbian"],
  ["Seychelles", "Seychellois"],
  ["Sierra Leone", "Sierra Leonean"],
  ["Singapore", "Singaporean"],
  ["Slovakia", "Slovak"],
  ["Slovenia", "Slovenian"],
  ["Solomon Islands", "Solomon Islander"],
  ["Somalia", "Somali"],
  ["South Africa", "South African"],
  ["South Korea", "South Korean"],
  ["South Sudan", "South Sudanese"],
  ["Spain", "Spanish"],
  ["Sri Lanka", "Sri Lankan"],
  ["Sudan", "Sudanese"],
  ["Suriname", "Surinamese"],
  ["Sweden", "Swedish"],
  ["Switzerland", "Swiss"],
  ["Syria", "Syrian"],
  ["Taiwan", "Taiwanese"],
  ["Tajikistan", "Tajik"],
  ["Tanzania", "Tanzanian"],
  ["Thailand", "Thai"],
  ["Timor-Leste", "Timorese"],
  ["Togo", "Togolese"],
  ["Tonga", "Tongan"],
  ["Trinidad and Tobago", "Trinidadian and Tobagonian"],
  ["Tunisia", "Tunisian"],
  ["Turkey", "Turkish"],
  ["Turkmenistan", "Turkmen"],
  ["Tuvalu", "Tuvaluan"],
  ["Uganda", "Ugandan"],
  ["Ukraine", "Ukrainian"],
  ["United Arab Emirates", "Emirati"],
  ["United Kingdom", "British"],
  ["United States", "American"],
  ["Uruguay", "Uruguayan"],
  ["Uzbekistan", "Uzbek"],
  ["Vanuatu", "Ni-Vanuatu"],
  ["Vatican City", "Vatican"],
  ["Venezuela", "Venezuelan"],
  ["Vietnam", "Vietnamese"],
  ["Yemen", "Yemeni"],
  ["Zambia", "Zambian"],
  ["Zimbabwe", "Zimbabwean"],
];

// Common alternative country spellings found in older saved data.
const COUNTRY_ALIASES: Record<string, string> = {
  usa: "American",
  us: "American",
  "united states of america": "American",
  america: "American",
  uk: "British",
  "great britain": "British",
  england: "British",
  "ivory coast": "Ivorian",
  "cote d'ivoire": "Ivorian",
  "czech republic": "Czech",
  swaziland: "Swazi",
  burma: "Burmese",
  myanmar: "Burmese",
  drc: "Congolese (DRC)",
  "dr congo": "Congolese (DRC)",
};

export const NATIONALITIES: string[] = COUNTRY_NATIONALITIES.map(([, nationality]) => nationality).sort((a, b) =>
  a.localeCompare(b),
);

const byNationality = new Map(NATIONALITIES.map((n) => [n.toLowerCase(), n]));
const byCountry = new Map(COUNTRY_NATIONALITIES.map(([country, n]) => [country.toLowerCase(), n]));

/** Returns the listed nationality for an exact (case-insensitive) nationality match, else null. */
export function findNationality(value: string | null | undefined): string | null {
  return byNationality.get(String(value ?? "").trim().toLowerCase()) ?? null;
}

/**
 * Maps a stored value to its listed nationality, converting legacy country
 * names (e.g. "Namibia" → "Namibian"). Unknown values are returned trimmed.
 */
export function normalizeNationality(value: string | null | undefined): string {
  const trimmed = String(value ?? "").trim();
  const key = trimmed.toLowerCase();
  return byNationality.get(key) ?? byCountry.get(key) ?? COUNTRY_ALIASES[key] ?? trimmed;
}
